package com.cleanroommc.retrosophisticatedbackpacks.client.gui

import com.cleanroommc.modularui.drawable.ItemDrawable
import com.cleanroommc.modularui.drawable.UITexture
import com.cleanroommc.retrosophisticatedbackpacks.Tags
import net.minecraft.init.Items
import net.minecraft.item.ItemStack
import net.minecraft.util.ResourceLocation

object RSBTextures {
    private val ICON_LOCATION = ResourceLocation(Tags.MOD_ID, "gui/icons")

    val CHECK_ICON = icon("check", 0, 0)
    val CROSS_ICON = icon("cross", 16, 0)

    val MATCH_NBT_ICON = icon("consider_nbt", 32, 0)
    val IGNORE_NBT_ICON = icon("ignore_nbt", 48, 0)

    val COMPLETE_HUNGER_ICON = icon("complete_hunger", 96, 0)
    val HALF_HUNGER_ICON = icon("half_hunger", 112, 0)
    val IMMEDIATE_HUNGER_ICON = icon("impose_hunger", 128, 0)

    val MATCH_DURABILITY_ICON = icon("consider_duration", 0, 16)
    val IGNORE_DURABILITY_ICON = icon("ignore_duration", 16, 16)

    val HALF_HEART_ICON = icon("half_heart", 96, 16)
    val IGNORE_HALF_HEART_ICON = icon("ignore_half_heart", 112, 16)

    val BY_MOD_ID_ICON = icon("by_mod_id", 32, 16)
    val BY_ITEM_ICON = ItemDrawable(ItemStack(Items.APPLE))

    val IN_OUT_ICON = icon("in_out", 0, 32)
    val IN_ICON = icon("in", 16, 32)
    val OUT_ICON = icon("out", 32, 32)
    val PUMP_INPUT_ICON = icon("pump_input", 144, 0)
    val PUMP_OUTPUT_ICON = icon("pump_output", 160, 0)
    val PUMP_WORLD_ICON = icon("pump_world", 176, 0)
    val PUMP_NO_WORLD_ICON = icon("pump_no_world", 192, 0)
    val PUMP_HAND_ICON = icon("pump_hand", 208, 0)
    val PUMP_NO_HAND_ICON = icon("pump_no_hand", 224, 0)
    val PUMP_FLUID_HANDLER_ICON = icon("pump_fluid_handler", 0, 112)
    val PUMP_NO_FLUID_HANDLER_ICON = icon("pump_no_fluid_handler", 16, 112)

    val ADD_ICON = icon("add", 96, 32)
    val REMOVE_ICON = icon("remove", 112, 32)
    val BRAIN_ICON = icon("brain", 128, 32)
    val ANVIL_NAME_BACKGROUND = controlIcon(28, 99, 100, 16)
    val ANVIL_NAME_BACKGROUND_DISABLED = controlIcon(28, 115, 100, 16)
    val ANVIL_PLUS_SIGN = controlIcon(113, 203, 13, 13)
    val ANVIL_ARROW = controlIcon(56, 221, 14, 15)
    val ANVIL_RED_CROSS = controlIcon(113, 216, 15, 15)

    val ONE_IN_FOUR_SLOT_ICON = icon("one_in_four_slot", 0, 80)
    val ALL_FOUR_SLOT_ICON = icon("all_in_four_slot", 16, 80)
    val NO_SORT_ICON = icon("no_sort", 32, 80)
    val NONE_FOUR_SLOT_ICON = icon("none_in_four_slot", 48, 80)
    val BACK_TO_BACKPACK_ICON = icon("back_to_backpack", 64, 80)

    val SETTING_ICON = icon("setting", 16, 96)

    val MATCH_ORE_DICT_ICON = icon("consider_ore_dict", 112, 96)
    val IGNORE_ORE_DICT_ICON = icon("ignore_ore_dict", 128, 96)

    val TOGGLE_DISABLE_ICON = icon("disable", 0, 128, 4, 10)
    val TOGGLE_ENABLE_ICON = icon("enable", 4, 128, 4, 10)

    val SOLID_UP_ARROW_ICON = icon("solid_up_arrow", 0, 144, 12, 12)
    val SMALL_A_ICON = icon("small_a", 24, 144, 12, 12)
    val SMALL_1_ICON = icon("small_1", 36, 144, 12, 12)
    val SMALL_O_ICON = icon("small_ore_dict", 64, 144, 12, 12)

    val SMALL_M_ICON = icon("small_m", 0, 156, 12, 12)
    val SOLID_DOWN_ARROW_ICON = icon("solid_down_arrow", 12, 156, 12, 12)
    val DOT_DOWN_ARROW_ICON = icon("dot_down_arrow", 24, 156, 12, 12)
    val DOT_UP_ARROW_ICON = icon("dot_up_arrow", 36, 156, 12, 12)

    val LEFT_ARROW_ICON = icon("left_arrow", 32, 48)
    val DOWN_ARROW_ICON = icon("down_arrow", 48, 48)
    val BACKPACK_SETTINGS_ICON = icon("backpack_settings", 64, 48)
    val ITEM_DISPLAY_SETTINGS_ICON = icon("item_display_settings", 112, 64)
    val ITEM_DISPLAY_ROTATE_ICON = icon("item_display_rotate", 128, 64)
    val DISPLAY_SIDE_FRONT_ICON = icon("display_side_front", 144, 64)
    val DISPLAY_SIDE_LEFT_ICON = icon("display_side_left", 160, 64)
    val DISPLAY_SIDE_RIGHT_ICON = icon("display_side_right", 176, 64)

    val STANDARD_BUTTON = UITexture.builder()
        .location(Tags.MOD_ID, "gui/gui_controls.png")
        .imageSize(256, 256)
        .xy(29, 0, 18, 18)
        .build()
    val STANDARD_BUTTON_HOVERED = UITexture.builder()
        .location(Tags.MOD_ID, "gui/gui_controls.png")
        .imageSize(256, 256)
        .xy(47, 0, 18, 18)
        .build()
    val SMALL_BUTTON = UITexture.builder()
        .location(Tags.MOD_ID, "gui/gui_controls.png")
        .imageSize(256, 256)
        .xy(29, 18, 12, 12)
        .build()
    val SMALL_BUTTON_HOVERED = UITexture.builder()
        .location(Tags.MOD_ID, "gui/gui_controls.png")
        .imageSize(256, 256)
        .xy(41, 18, 12, 12)
        .build()
    val CONTEXT_BUTTON_LEFT = buttonPiece(29, 0, 16, 18)
    val CONTEXT_BUTTON_LEFT_HOVERED = buttonPiece(47, 0, 16, 18)
    val CONTEXT_BUTTON_MIDDLE = buttonPiece(31, 0, 14, 18)
    val CONTEXT_BUTTON_MIDDLE_HOVERED = buttonPiece(49, 0, 14, 18)
    val CONTEXT_BUTTON_RIGHT = buttonPiece(31, 0, 16, 18)
    val CONTEXT_BUTTON_RIGHT_HOVERED = buttonPiece(49, 0, 16, 18)

    val BIG_SLOT_TEXTURE = UITexture.builder()
        .location(Tags.MOD_ID, "gui/gui_controls.png")
        .imageSize(256, 256)
        .xy(71, 216, 26, 26)
        .build()

    val CRAFTING_ARROW = UITexture.builder()
        .location(Tags.MOD_ID, "gui/gui_controls.png")
        .imageSize(256, 256)
        .xy(97, 209, 16, 16)
        .build()
    val TANK_ARROW = UITexture.builder()
        .location(Tags.MOD_ID, "gui/gui_controls.png")
        .imageSize(256, 256)
        .xy(97, 216, 15, 8)
        .build()
    val MEMORIZED_SLOT_OVERLAY = UITexture.builder()
        .location(Tags.MOD_ID, "gui/gui_controls.png")
        .imageSize(256, 256)
        .xy(77, 0, 16, 16)
        .build()
    val SLOT_SELECTION = UITexture.builder()
        .location(Tags.MOD_ID, "gui/gui_controls.png")
        .imageSize(256, 256)
        .xy(93, 0, 24, 24)
        .build()
    val SLOT_BACKGROUND = UITexture.builder()
        .location(Tags.MOD_ID, "gui/slots_background.png")
        .imageSize(256, 256)
        .xy(0, 0, 18, 18)
        .build()
    val SLOTS_BACKGROUND = UITexture.fullImage(Tags.MOD_ID, "gui/slots_background.png")
    val STORAGE_BACKGROUND_9 = UITexture.fullImage(Tags.MOD_ID, "gui/storage_background_9.png")
    val STORAGE_BACKGROUND_9_WIDER = UITexture.fullImage(Tags.MOD_ID, "gui/storage_background_9_wider.png")
    val STORAGE_BACKGROUND_12 = UITexture.fullImage(Tags.MOD_ID, "gui/storage_background_12.png")
    val STORAGE_BACKGROUND_12_WIDER = UITexture.fullImage(Tags.MOD_ID, "gui/storage_background_12_wider.png")
    val EMPTY_TANK_INPUT_SLOT = UITexture.fullImage(Tags.MOD_ID, "item/empty_tank_input_slot.png")
    val EMPTY_TANK_OUTPUT_SLOT = UITexture.fullImage(Tags.MOD_ID, "item/empty_tank_output_slot.png")
    val EMPTY_BATTERY_INPUT_SLOT = UITexture.fullImage(Tags.MOD_ID, "item/empty_battery_input_slot.png")
    val EMPTY_BATTERY_OUTPUT_SLOT = UITexture.fullImage(Tags.MOD_ID, "item/empty_battery_output_slot.png")
    val EMPTY_UPGRADE_SLOT = UITexture.fullImage(Tags.MOD_ID, "item/empty_upgrade_slot.png")

    val TANK_OVERLAY = UITexture.builder()
        .location(Tags.MOD_ID, "gui/gui_controls.png")
        .imageSize(256, 256)
        .xy(47, 30, 16, 18)
        .build()
    val BATTERY_OVERLAY = UITexture.builder()
        .location(Tags.MOD_ID, "gui/gui_controls.png")
        .imageSize(256, 256)
        .xy(47, 56, 16, 18)
        .build()
    val BATTERY_CHARGE = UITexture.builder()
        .location(Tags.MOD_ID, "gui/gui_controls.png")
        .imageSize(256, 256)
        .xy(47, 74, 16, 6)
        .build()
    val BAR_BACKGROUND_TOP = barBackground(29, 30)
    val BAR_BACKGROUND_MIDDLE = barBackground(29, 48)
    val BAR_BACKGROUND_BOTTOM = barBackground(29, 66)
    val SHIFT_CLICK_OPEN_TAB_ON = icon("shift_click_open_tab_on", 80, 32)
    val SHIFT_CLICK_OPEN_TAB_OFF = icon("shift_click_open_tab_off", 64, 96)
    val KEEP_TAB_OPEN_ON = icon("keep_tab_open_on", 80, 80)
    val KEEP_TAB_OPEN_OFF = icon("keep_tab_open_off", 80, 96)
    val KEEP_SEARCH_PHRASE_ON = icon("keep_search_phrase_on", 208, 32)
    val KEEP_SEARCH_PHRASE_OFF = icon("keep_search_phrase_off", 224, 32)
    val SEARCH_ICON = icon("search", 208, 32)
    val ANOTHER_PLAYER_CAN_OPEN_ON = icon("another_player_can_open_on", 176, 32)
    val ANOTHER_PLAYER_CAN_OPEN_OFF = icon("another_player_can_open_off", 192, 32)

    private fun icon(name: String, x: Int, y: Int, w: Int = 16, h: Int = 16): UITexture =
        UITexture.builder()
            .location(ICON_LOCATION)
            .imageSize(256, 256)
            .xy(x, y, w, h)
            .name(name)
            .build()

    private fun barBackground(x: Int, y: Int): UITexture =
        UITexture.builder()
            .location(Tags.MOD_ID, "gui/gui_controls.png")
            .imageSize(256, 256)
            .xy(x, y, 18, 18)
            .build()

    private fun buttonPiece(x: Int, y: Int, w: Int, h: Int): UITexture =
        UITexture.builder()
            .location(Tags.MOD_ID, "gui/gui_controls.png")
            .imageSize(256, 256)
            .xy(x, y, w, h)
            .build()

    private fun controlIcon(x: Int, y: Int, w: Int = 16, h: Int = 16): UITexture =
        UITexture.builder()
            .location(Tags.MOD_ID, "gui/gui_controls.png")
            .imageSize(256, 256)
            .xy(x, y, w, h)
            .build()
}
